### ISSUE TITLE
JRuby version has outdated lock_jar dependency

### ISSUE THREAD

**Issue by pangloss** [cognitect/transit-ruby#17]
Can you please release an updated version that I can bundle with lock_jar 0.12.x? The lock_jar project has had numerous bug fixes recently, one of which I require in my project that uses transit-ruby.

Thanks!

**Comment by dchelimsky** [comment]
Just released transit-ruby-0.8.591 with this change in the java gem (transit-ruby-0.8.591-java.gem).

**Comment by pangloss** [comment]
Thank you!
