### ISSUE TITLE
Support for JRuby 9000

### ISSUE THREAD

**Issue by pangloss** [cognitect/transit-ruby#18]
Is there any plan for supporting the current version of JRuby?

**Comment by jkutner** [comment]
It seems that with the latest version on Rubygems ([0.8.602](https://rubygems.org/gems/transit-ruby/versions/0.8.602)), the transit-ruby fails install because it tries to use `oj` Gem, which has native extensions and doesn't work on JRuby.

Using the following in my `Gemfile` works though:

```ruby
gem 'transit-ruby', git: 'https://github.com/cognitect/transit-ruby'
```

Will there be a release soon?

**Comment by dchelimsky** [comment]
I'd like to be sure the next release supports jruby-1.7.27, jruby-9.0.0.0, and the latest (currently jruby-9.1.9.0).

Here's the current status:

- On jruby-1.7.27, there are downstream dependency conflicts that need to be resolved before I can even test it.
- On jruby-9.0.0.0 and 9.1.9.0
  - passes the specs in the transit-ruby repo
  - passes [https://github.com/cognitect/transit-format/blob/master/TESTING.md#testing-transit-implementations](bin/verify) for msgpack
  - fails bin/verify for json and json-verbose - this needs to be resolved to move forward.

This project does not accept PRs, but If anybody wants to help resolve these issues, please report your findings here and I'll carry on next time I am able.

**Comment by dchelimsky** [comment]
@jkutner you have to use the `java`:

```gem search transit-ruby

*** REMOTE GEMS ***

transit-ruby (0.8.602, 0.8.597 java)```

The 0.8.597 version has not been tested with jruby >= 9.0.0.0, but it was tested with 1.7.13 through 16.

So, for now, your best bet is what you've done with the `Gemfile`.
