### ISSUE TITLE
Loosen addressable dependency requirement

### ISSUE THREAD

**Issue by tdg5** [cognitect/transit-ruby#20]
Hello!

I was just wondering if it might be possible to loosen the dependency on `addressable`? Currently, the requirement is `~> 2.3.6`, and I was hoping that it might be possible to loosen the requirement by dropping the patch portion of the version so the new requirement would be `~> 2.3`.

The more strict requirement is giving me dependency trouble given the popularity of the `addressable` library. I tried reducing the restriction and ran the specs on MRI 2.3.0 and didn't have any problems.

Alternatively, if you want to bump the dependency to `~> 2.5.0`, that'd help my problem in the near term, but I may be back again to bug you later.

I created a branch here with the change if it happens to interest you: https://github.com/tdg5/transit-ruby/tree/loosen-addressable-requirement

Here's the specific diff: https://github.com/tdg5/transit-ruby/commit/f6ec54ffdcae9039bb6a4d3d5721dbeb6f29a76e

If I can answer any questions or offer any other assistance, please let me know. Thanks!

**Comment by maiwald** [comment]
Hi there,

we have the same issue preventing us from using transit.

**Comment by dchelimsky** [comment]
I'll try to take a look at this on Friday.

**Comment by devn** [comment]
Bumping because we needed to fork to deal with this, but I would have preferred not to.

**Comment by dchelimsky** [comment]
I've got this addressed on a branch but I have to do some more testing across Ruby versions (specifically JRuby versions) before releasing. Probably won't get to that before this coming Friday, but it's in progress.

**Comment by dchelimsky** [comment]
Fixed in 99795d3
Released in transit-ruby-0.8.602
